#!/usr/bin/env python3
"""Shared helpers for the repo-hygiene scripts. Python 3.8+, standard library only."""
import os
import re
import subprocess
import sys

LINE_COMMENT = {
    '//': ['.cs', '.java', '.kt', '.kts', '.go', '.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx', '.rs', '.swift',
           '.c', '.h', '.cc', '.cpp', '.hpp', '.m', '.mm', '.scala', '.dart', '.php', '.groovy', '.gradle',
           '.proto', '.axaml.cs', '.razor', '.fs'],
    '#': ['.py', '.sh', '.bash', '.zsh', '.rb', '.yml', '.yaml', '.toml', '.ps1', '.psm1', '.psd1', '.pl',
          '.r', '.mk', '.cmake', '.tf', '.ex', '.exs', '.nim'],
    '--': ['.sql', '.lua', '.hs', '.elm'],
    'REM': ['.bat', '.cmd'],
}
BLOCK_COMMENT = {
    ('/*', '*/'): LINE_COMMENT['//'] + ['.css', '.scss', '.less'],
    ('<!--', '-->'): ['.xml', '.axaml', '.xaml', '.html', '.htm', '.csproj', '.props', '.targets', '.svg', '.vue'],
    ('<#', '#>'): ['.ps1', '.psm1'],
}
COMMENT_EXTS = {e for v in LINE_COMMENT.values() for e in v} | {e for v in BLOCK_COMMENT.values() for e in v}

# Lines that look like comments but are instructions to a tool; never counted as "removable" comments.
DIRECTIVE_RE = re.compile(
    r'^\s*(?:#!|//\s*(?:noinspection|<auto-generated|nolint|go:|\+build|@ts-|eslint|prettier|swiftlint|'
    r'region|endregion|ReSharper|pragma)|#\s*(?:shellcheck|-\*-|type:|noqa|pylint|pragma|fmt:|region|endregion|'
    r'requires|nosec)|//\s*<|\s*#\s*requires)', re.I)
LICENSE_RE = re.compile(r'copyright|spdx-license|licensed under|all rights reserved', re.I)


def run(*args, cwd=None):
    r = subprocess.run(args, cwd=cwd, capture_output=True, check=False)
    r.stdout = r.stdout.decode('utf-8', 'replace')
    r.stderr = r.stderr.decode('utf-8', 'replace')
    return r


def repo_root(path='.'):
    r = run('git', '-C', path, 'rev-parse', '--show-toplevel')
    if r.returncode != 0:
        sys.exit('not a git repository: ' + path)
    return r.stdout.strip()


def tracked(root):
    out = subprocess.run(['git', '-C', root, 'ls-files', '-z'], capture_output=True, check=True).stdout
    return [p for p in out.decode('utf-8', 'surrogateescape').split('\0') if p]


def read_text(root, rel, max_bytes=3_000_000):
    """Decoded text, or None for binary / unreadable / huge files."""
    try:
        with open(os.path.join(root, rel), 'rb') as f:
            data = f.read(max_bytes + 1)
    except OSError:
        return None
    if len(data) > max_bytes or b'\0' in data[:8192]:
        return None
    return data.decode('utf-8', 'replace')


def ext_of(path):
    base = os.path.basename(path).lower()
    i = base.rfind('.')
    return base[i:] if i > 0 else ''


def line_prefix_for(path):
    e = ext_of(path)
    for prefix, exts in LINE_COMMENT.items():
        if e in exts:
            return prefix
    return None


def is_pure_comment_line(path, line):
    """True when the whole line is a single-line comment of the file's language (heuristic)."""
    s = line.strip()
    if not s:
        return False
    prefix = line_prefix_for(path)
    if prefix == 'REM':
        return bool(re.match(r'(?i)(rem\b|::)', s))
    if prefix and s.startswith(prefix):
        return True
    e = ext_of(path)
    for (open_, _close), exts in BLOCK_COMMENT.items():
        if e in exts and s.startswith(open_):
            return True
    return False


def comment_flags(path, lines):
    """Per line: True when the whole line is comment text (line comments and block comments, tracked across lines)."""
    e = ext_of(path)
    prefix = line_prefix_for(path)
    blocks = [(o, c) for (o, c), exts in BLOCK_COMMENT.items() if e in exts]
    flags, end = [], None
    for ln in lines:
        s = ln.strip()
        if end is not None:
            if end in s:
                flags.append(not s.split(end, 1)[1].strip())
                end = None
            else:
                flags.append(True)
            continue
        if not s:
            flags.append(False)
            continue
        if prefix == 'REM':
            flags.append(bool(re.match(r'(?i)(rem|::)', s)))
            continue
        if prefix and s.startswith(prefix):
            flags.append(True)
            continue
        for o, c in blocks:
            if s.startswith(o):
                rest = s[len(o):]
                if c in rest:
                    flags.append(not rest.split(c, 1)[1].strip())
                else:
                    flags.append(True)
                    end = c
                break
        else:
            flags.append(False)
    return flags


def is_directive(line):
    return bool(DIRECTIVE_RE.match(line))


HISTORY_DIR_RE = re.compile(
    r'(^|/)(plans?|reports?|archive[sd]?|history|old|legacy|design|drafts?|retros?|postmortems?|'
    r'worklog|notes?|sessions?|changelogs?)(/|$)', re.I)
DATED_NAME_RE = re.compile(r'(19|20)\d\d[-_]?(0[1-9]|1[0-2])[-_]?(0[1-9]|[12]\d|3[01])')
TEST_PATH_RE = re.compile(r'(^|/)([\w.-]*[._-])?(tests?|__tests__|spec|specs)(/|$)|[._-](test|tests|spec)\.[a-z]+$|Tests?\.[a-z]+$', re.I)
INSTRUCTION_FILES_RE = re.compile(
    r'(^|/)(AGENTS\.md|CLAUDE\.md|GEMINI\.md|\.cursorrules|SKILL\.md|copilot-instructions\.md|CONTRIBUTING\.md)$')
